---
name: Docker

on:
  workflow_call:
    

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup docker build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Download a build artifact
      uses: actions/download-artifact@v4
      with:
        name: build_program

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: raphaelfontoura
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: raphaelfontoura/go_ci:${{ github.ref_name }}
        
